### ISSUE TITLE
Tags explanation

### ISSUE THREAD

**Issue by SilvioMessi** [dhfbk/tint#14]
Hi.
I'm using Tint for POS tagging some Italian sentences.
Fore example  the tags returned for the sentence "Posso avere una pizza margherita?" are:
- Posso ->  VM
- avere -> V
- una -> RI
- pizza -> S
- margherita -> S
- ? -> FS

Where can I found the explanation of tags?

Thank you.

**Comment by ziorufus** [comment]
You can find the list of tags here: http://www.italianlp.it/docs/ISST-TANL-POStagset.pdf

**Comment by SilvioMessi** [comment]
Thank you so much!

**Comment by nicolasfeyer** [comment]
[https://web.archive.org/web/20241005030906/https://www.italianlp.it/docs/ISST-TANL-POStagset.pdf](https://web.archive.org/web/20241005030906/https://www.italianlp.it/docs/ISST-TANL-POStagset.pdf)
