### ISSUE TITLE
No NER in CONLL format

### ISSUE THREAD

**Issue by apiatti** [dhfbk/tint#16]
I am using TINT via command-line and I noticed that when the output is set to the CONLL format, no information about the name entity is displayed, despite the output tells me:
`INFO  edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner`

Another issue I am having is that I get this warning:
`warning: no language set, no open-class tags specified, and no closed-class tags specified; assuming ALL tags are open class tags
`
Despite this last warning everything seems to work fine.
Are those bugs, bad configurations? 
Thanks!

**Comment by ziorufus** [comment]
Che [CoNLL format](http://ufal.mff.cuni.cz/conll2009-st/task-description.html) does not include the NER, therefore if you choose that output format you won't have it. Just use JSON to get it.
The other issue is related to the POS model, but you can ignore it.

**Comment by apiatti** [comment]
well, thanks a lot!
