### ISSUE TITLE
Openie, naturallogicannotation 

### ISSUE THREAD

**Issue by GioAlba** [dhfbk/tint#20]
hi, does this project support openie and naturallogic? tranks
Giovanni

**Comment by ziorufus** [comment]
Unfortunately not.

**Comment by WEMAPP** [comment]
I've been trying to use stanford core npl recently.
I just wanted to ask you if you think it's possible, with the current tools, for extract the topic of a sentence in Italian language.
It seems to me that stanford in English works quite well. But I can not figure out how to integrate your product into a pure StanfordCoreNPL project.

**Comment by ziorufus** [comment]
Tint uses the Java structure of CoreNLP, but all the included models are trained on Italian language. If you work with texts in Italian, you can use easily the Tint models into a pure StanfordCoreNLP project.
Regarding topic, Tint does not include a topic extractor out-of-the-box, but you can use [Keyphrase Digger](https://dh.fbk.eu/technologies/kd), that extract keywords from texts and provides a wrapper for CoreNLP.
In addition, you can detect the topic using [TheWikiMachine](http://ml.apnetwork.it/demo/demo-annotate.html). You can install on your server following the [documentation](https://bitbucket.org/fbk/airpedia/wiki/Tutorial), and then you can use it in Tint through the [FCW](https://github.com/fbk/fcw) project, that includes a wrapper for TWM, `fcw-linking`. This procedure is not very straightforward as it involves a lot of different projects.

**Comment by WEMAPP** [comment]
Thank you so much. you did something spectacular !!!!
I will try to install the software by following the instructions.
I can not just find a copy of the license. How can the software be used?

**Comment by ziorufus** [comment]
Tint is licensed under GPL, but the models belong to the Italian Universal Dependencies that are released under CC BY-NC-SA (no commercial use, then). TheWikiMachine and KD are released under Apache license and the TWM models are generated using Wikipedia, therefore commercial use is ok. Apart from KD, all tools are open source.

**Comment by WEMAPP** [comment]
Thanks and congratulations again for your wonderful work.
Giovanni

**Comment by ziorufus** [comment]
You're welcome!
