### ISSUE TITLE
Order of dependencies list

### ISSUE THREAD

**Issue by vicawil** [dhfbk/tint#25]
It seems that using the default configuration always results in in dependency lists, where the root element is the first element, whereas every other element is in order. Is this intended? As I wish to iterate over tokens and basic-dependencies in parallel, this forces me to resort the list (key: dependent) prior to processing.

Example:
> Le politiche di unione economica e monetaria dell'Unione europea hanno portato nel 1999 all'introduzione di una moneta unica.

JSON-Snippet:
```
"basic-dependencies": [
        {
          "dep": "ROOT",
          "governor": 0,
          "governorGloss": "ROOT",
          "dependent": 12,
          "dependentGloss": "portato"
        },
        {
          "dep": "det",
          "governor": 2,
          "governorGloss": "politiche",
          "dependent": 1,
          "dependentGloss": "Le"
        },
        {
          "dep": "nsubj",
          "governor": 12,
          "governorGloss": "portato",
          "dependent": 2,
          "dependentGloss": "politiche"
        },
        {
          "dep": "case",
          "governor": 4,
          "governorGloss": "unione",
          "dependent": 3,
          "dependentGloss": "di"
        ...
```

**Comment by ziorufus** [comment]
Tint uses the original CoreNLP dependencies module, therefore I cannot answer this question. Try to contact the Stanford CoreNLP staff.
