### ISSUE TITLE
italian-big.tagger missing from latest nightly build

### ISSUE THREAD

**Issue by vicawil** [dhfbk/tint#29]
I've come across another issue, this time in the nightly build:  The `italian-big.tagger` is not contained in `lib/tint-models-1.0-SNAPSHOT.jar`. Looking at the develop branch of the git repo, it's still there (https://github.com/dhfbk/tint/tree/develop/tint-models/src/main/resources/models). Has this been excluded on purpose?

**Comment by ziorufus** [comment]
We deleted it by mistake, we added it again in the `develop` version. We'll release a new (possibly) stable version soon. Thank you again for your message.
