### ISSUE TITLE
Characters with accents misinterpreted

### ISSUE THREAD

**Issue by lonevetad** [dhfbk/tint#34]
No matter if the character is Upper (È) or lower (è), Tint split it as a double question mark (?) and, so, produces dependency nodes accordingly (i.e., nodes having "pos=X").
The sentence is "è la spada laser di tuo padre." and the JSON the pipeline produces is:

[18.txt](https://github.com/dhfbk/tint/files/5396038/18.txt)

**Comment by ziorufus** [comment]
This is weird. Are you using UTF-8? Can you check the file encoding?

**Comment by WEMAPP** [comment]
hello 
i also have the same problem. 
It works fine with the get but for the post it doesn't seem to accept UTF-8

**Comment by ziorufus** [comment]
Fixed in the new release.
